// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6AeW2-lw2IlZqqwqKAkG0U4DP_Wc1imU',
    appId: '1:1028304111781:web:a2e941d15f2f508982654c',
    messagingSenderId: '1028304111781',
    projectId: 'betaai-f9344',
    authDomain: 'betaai-f9344.firebaseapp.com',
    databaseURL: 'https://betaai-f9344-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'betaai-f9344.appspot.com',
    measurementId: 'G-10E7EJ7K0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByLBl17C5qXq5u8PEoEoXWSklWATSyZT8',
    appId: '1:1028304111781:android:897f2acc8bd8ffce82654c',
    messagingSenderId: '1028304111781',
    projectId: 'betaai-f9344',
    databaseURL: 'https://betaai-f9344-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'betaai-f9344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc66o4rO5muodqUqvB3odBzDeus0XThAg',
    appId: '1:1028304111781:ios:1f2b18dd03d7e67282654c',
    messagingSenderId: '1028304111781',
    projectId: 'betaai-f9344',
    databaseURL: 'https://betaai-f9344-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'betaai-f9344.appspot.com',
    iosClientId: '1028304111781-a89nhg75fsugalqccle336m6864glvio.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc66o4rO5muodqUqvB3odBzDeus0XThAg',
    appId: '1:1028304111781:ios:1f2b18dd03d7e67282654c',
    messagingSenderId: '1028304111781',
    projectId: 'betaai-f9344',
    databaseURL: 'https://betaai-f9344-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'betaai-f9344.appspot.com',
    iosClientId: '1028304111781-a89nhg75fsugalqccle336m6864glvio.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
